### ISSUE TITLE
changing tracks automatically after around 40 min

### ISSUE THREAD

**Issue by amanthegreatone** [timoknapp/sound-on-fire#27]
was listening to long sets (1.5 hr+) and twice it happened after around 40min it skipped to the next track in the playlist. Will try to play some more long sets and see if this is a persistent issue

**Comment by timoknapp** [comment]
Hi @amanthegreatone ,
Thanks for the feedback. I will take a closer look into it. In case you notice further details about the bug, I would appreciate a more fine-grained description.

Regards
Timo

**Comment by timoknapp** [comment]
Hi @amanthegreatone , 
I now also had a look into it and it seems like the audioplayer looses the connection to the stream after a while (~40 minutes). I am going to have a deeper look and plan to fix it asap :)

Cheers
Timo

**Comment by timoknapp** [comment]
Hi @amanthegreatone ,

It seems that I found the problem. It will be solved within [this](https://github.com/timoknapp/sound-on-fire/tree/feat/change-audioplayer) feature branch. The next release will include the bugfix.

Regards
Timo

**Comment by timoknapp** [comment]
Hi @amanthegreatone ,

the bug should now be resolved in [Release v1.3.0](https://github.com/timoknapp/sound-on-fire/releases/tag/v1.3.0%2B117)

Regards
Timo
