### ISSUE TITLE
Bluethooth Keyboard not working

### ISSUE THREAD

**Issue by hahaxd35** [timoknapp/sound-on-fire#49]
in search.

Thanks for your grate App!

**Comment by timoknapp** [comment]
Hi @hahaxd35 ,

What exactly do you mean by "Bluetooth keyboard not working"? As the App was made to be used mainly with Fire TV, it is supposed to be controlled by the regular remote control of the smart TV (Fire TV). So the App was never intended to be controlled by a real keyboard.

Regards
Timo

**Comment by hahaxd35** [comment]
Ach du bist ja deutsch :D 

Also ich kann die Bluethooth Tastertur in jedem "input" auf dem FireTV nutzen. In der suchleiste in deiner App klappt das leider nicht. 

weiß nicht wie das zu stande kommt

**Comment by timoknapp** [comment]
I will close this bug, as the behaviour is intended. In case you are still interested in this feature, you are happily invited to create a pull request.

Regards
