### ISSUE TITLE
login

### ISSUE THREAD

**Issue by blackjack4494** [timoknapp/sound-on-fire#7]
That may help you
https://gist.github.com/blackjack4494/c67adb54aaf2db79f394279fc9d76bb6
if you want to implement login. Private sets/playlists like soundcloud weekly will be available then. Also higher quality songs if you have a subscription

**Comment by timoknapp** [comment]
Hi @blackjack4494 ,

Thanks for sharing the gist. By now a login is not yet planned. If you are aiming for such a feature, you are free to issue a PR.

Nevertheless I would aim for a more user friendly way of  login. E.g. like YouTube ist doing it via code or QR.
